// <auto-generated />
namespace TP01_Module06.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class artMartials : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(artMartials));
        
        string IMigrationMetadata.Id
        {
            get { return "202004232032568_artMartials"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
